class AppStrings {
  static String currentLanguage = "en";

  static final Map<String, Map<String, String>> translations = {
    "en": {
      "language": "Language",
      "settings": "Settings",
      "notes": "Notes",
      "home": "Home",
      "search": "Search",
      "profile": "Profile",
      "save": "Save",
      "delete": "Delete",
      "edit": "Edit",
      "share": "Share",
      "cancel": "Cancel",
      "add_note": "Add Note",
      "title": "Title",
      "content": "Content",
      "dark_mode": "Dark Mode",
      "light_mode": "Light Mode",
      "theme": "Theme",
      "pin": "Pin",
      "unpin": "Unpin",
      "favorites": "Favorites",
      "logout": "Logout",
      "back": "Back",
      "security": "Security",
      "backup_restore": "Backup & Restore",
      "about_noteapp": "About NoteApp",
      "english": "English",
      "light": "Light",
      "change_pin": "Change PIN",
      "delete_pin": "Delete PIN",
      "create_pin": "Create PIN",
      "pin_settings": "PIN Settings",
      "noteapp": "NoteApp",
      "developed_with_flutter": "Developed using Flutter & Firebase",
      "done": "Done",
      "all_notes": "All Notes",
      "about": "About",
      "no_data": "No Data",
      "about_description":
          "A simple notes application built with Flutter & Firebase.",
      "developer": "Developer: Rawan Rizk",
      "rights": "© 2026 All Rights Reserved",
      "note_title": "Note title",
      "write_something": "Write something...",
      "font_size": "Font Size",
    },

    "ar": {
      "language": "اللغة",
      "settings": "الإعدادات",
      "notes": "الملاحظات",
      "home": "الرئيسية",
      "search": "بحث",
      "profile": "الملف الشخصي",
      "save": "حفظ",
      "delete": "حذف",
      "edit": "تعديل",
      "share": "مشاركة",
      "cancel": "إلغاء",
      "add_note": "إضافة ملاحظة",
      "title": "العنوان",
      "content": "المحتوى",
      "dark_mode": "الوضع الداكن",
      "light_mode": "الوضع الفاتح",
      "theme": "المظهر",
      "pin": "تثبيت",
      "unpin": "إلغاء التثبيت",
      "favorites": "المفضلة",
      "logout": "تسجيل الخروج",
      "back": "رجوع",
      "security": "الأمان",
      "backup_restore": "النسخ الاحتياطي والاستعادة",
      "about_noteapp": "حول التطبيق",
      "english": "الإنجليزية",
      "light": "فاتح",
      "change_pin": "تغيير الرقم السري",
      "delete_pin": "حذف الرقم السري",
      "create_pin": "إنشاء رقم سري",
      "pin_settings": "إعدادات PIN",
      "noteapp": "نوت آب",
      "developed_with_flutter": "تم تطويره باستخدام Flutter و Firebase",
      "done": "تم",
      "all_notes": "كل الملاحظات",
      "about": "حول التطبيق",
      "no_data": "لا توجد بيانات",
      "about_description":
          "تطبيق ملاحظات بسيط مبني باستخدام Flutter و Firebase.",
      "developer": "المطور: روان رزق",
      "rights": "© 2026 جميع الحقوق محفوظة",
      "note_title": "عنوان الملاحظة",
      "write_something": "اكتبي ملاحظتك...",
      "font_size": "حجم الخط",
    },
  };

  static String tr(String key) {
    return translations[currentLanguage]?[key] ?? key;
  }
}